### PR TITLE
Generate tests coverage with pytest-cov plugin

### PR DESCRIPTION
**Pull request by kemskems**
See #44.

### CODE REVIEW

**Comment by fushar** [comment]
Can the developers run/see the coverage results locally?

**Comment by kemskems** [comment]
@fushar Of course. This is the point of this PR. Simply run `./manage.py test` and the coverage report will be printed to the terminal AND generated as HTML inside `htmlcov` directory.

**Comment by fushar** [comment]
@kemskems OK then :)

+1

**Comment by kemskems** [comment]
Great!

**Pull request merged**
