### PR TITLE
Create automated tests

### PR DESCRIPTION
**Pull request by kemskems**
See #13.

I used [Pytest](http://pytest.org/latest/) library for testing since I've heard many good things about it. To run the tests, simply run `py.test`.

**Summary:**
- Renamed `app.py` to `tululbot.py` to distinguish the module and the actual application object.
- Use Flask's built in application logger.
- Used [application factory pattern](http://flask.pocoo.org/docs/0.10/patterns/appfactories/) to make it easier injecting configuration for testing purposes. Without application factory pattern, I couldn't think any elegant way of configuring the app for testing. This is the best solution I've come up with. Suggestions are welcomed :-)
- Update Procfile to use `default_app` application object. This `default_app` gets its configuration from the environment variables, as usual.

**Caveat:**
- The command to run the app locally is now `python tululbot.py`. It's slightly longer than the previous one.

### CODE REVIEW

**Comment by kemskems** [comment]
Travis thinks this is a Ruby project so the builds failed. I guess we can safely ignore them.

**Comment by wazaundtechnik** [comment]
Please also update the README on how to run the test locally.

**Comment by kemskems** [comment]
@wazaundtechnik OK. Will do that tonight.

**Comment by wazaundtechnik** [comment]
LGTM. @fushar wants to check the test, perhaps? Does it work on your machine?

**Comment by wazaundtechnik** [comment]
I am sorry kems, could you please rebase with master upstream and edit the travis test yml accordingly?

**Comment by kemskems** [comment]
@wazaundtechnik done. Let's see if the build succeeds.

**Pull request merged**
